[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/xyproto/simplebolt"
  version = "3.4.0"
